
import java.awt.*;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.regex.*;
import javax.swing.InputMap;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/**
 * @author Sebastian
 */
public class FormReg extends javax.swing.JFrame {
	static ArrayList<Usuario> myList = new ArrayList<>();;
	static int ce = 0, flag = 0;

	/**
	 * Creates new form FormReg
	 */
	public FormReg() {
		initComponents();
		InputMap map2 = TxtConfEmail.getInputMap(TxtConfEmail.WHEN_FOCUSED);
		map2.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
		InputMap map1 = TxtConfContraseña.getInputMap(TxtConfContraseña.WHEN_FOCUSED);
		map1.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
		this.setLocationRelativeTo(null);
		this.setResizable(false);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")

	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		jPanel1 = new javax.swing.JPanel();
		lblNombre = new javax.swing.JLabel();
		TxtNombre = new javax.swing.JTextField();
		lblTipoID = new javax.swing.JLabel();
		TxtApellidos = new javax.swing.JTextField();
		lblApellidos1 = new javax.swing.JLabel();
		CombID = new javax.swing.JComboBox<>();
		lblNumID = new javax.swing.JLabel();
		TxtNumID = new javax.swing.JTextField();
		lblResidencia = new javax.swing.JLabel();
		CombResidencia = new javax.swing.JComboBox<>();
		lblNumCel = new javax.swing.JLabel();
		TxtNumCel = new javax.swing.JTextField();
		lblResidencia1 = new javax.swing.JLabel();
		CombNacionalidad = new javax.swing.JComboBox<>();
		lblEmail = new javax.swing.JLabel();
		TxtEmail = new javax.swing.JTextField();
		lblConfEmail = new javax.swing.JLabel();
		TxtConfEmail = new javax.swing.JTextField();
		TxtConfContraseña = new javax.swing.JTextField();
		lblContraseña = new javax.swing.JLabel();
		TxtContraseña = new javax.swing.JTextField();
		lblConfContraseña = new javax.swing.JLabel();
		CBoxPTI = new javax.swing.JCheckBox();
		CheckBoxTyC = new javax.swing.JCheckBox();
		BtnMetodos = new javax.swing.JButton();
		BtnRegistrar = new javax.swing.JButton();
		jPanel2 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jScrollPane1.setPreferredSize(new java.awt.Dimension(670, 750));

		jPanel1.setBackground(new java.awt.Color(204, 255, 255));
		jPanel1.setPreferredSize(new Dimension(650, 750));
		jPanel1.setPreferredSize(new java.awt.Dimension(650, 1100));

		lblNombre.setText("Nombres");

		lblTipoID.setText("Tipo de identificacion");

		lblApellidos1.setText("Apellidos");

		CombID.setModel(new javax.swing.DefaultComboBoxModel<>(
				new String[] { "SELECCIONE", "Cédula de ciudadanía", "Cédula de extranjería", "Pasaporte" }));
		CombID.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				CombIDActionPerformed(evt);
			}
		});

		lblNumID.setText("Número de documento");

		lblResidencia.setText("Lugar donde vives");

		CombResidencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "Barbosa", "Bello",
				"Caldas", "Copacabana", "Envigado", "Girardota", "Itagüi", "La Estrella", "Medellin", "Sabaneta" }));
		CombResidencia.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				CombResidenciaActionPerformed(evt);
			}
		});

		lblNumCel.setText("Número celular");

		lblResidencia1.setText("Nacionalidad");

		CombNacionalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Colombiano (a)", "Otro" }));
		CombNacionalidad.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				CombNacionalidadActionPerformed(evt);
			}
		});

		lblEmail.setText("Correo electrónico");

		lblConfEmail.setText("Confirmar correo electrónico");

		lblContraseña.setText("Contraseña");

		lblConfContraseña.setText("Confirmar contraseña");

		CBoxPTI.setForeground(new java.awt.Color(51, 153, 255));
		CBoxPTI.setText(
				"Autorizo el tratamiento de mis datos personales y acepto la Politica de Tratamiento de la Informacion");
		CBoxPTI.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				CBoxPTIActionPerformed(evt);
			}
		});

		CheckBoxTyC.setForeground(new java.awt.Color(0, 153, 255));
		CheckBoxTyC.setText("Acepto los terminos y condiciones");
		CheckBoxTyC.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				CheckBoxTyCActionPerformed(evt);
			}
		});

		BtnMetodos.setBackground(new java.awt.Color(204, 204, 204));
		BtnMetodos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		BtnMetodos.setText("Metodos");
		BtnMetodos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		BtnMetodos.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				BtnMetodosActionPerformed(evt);
			}
		});

		BtnRegistrar.setBackground(new java.awt.Color(0, 153, 255));
		BtnRegistrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		BtnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
		BtnRegistrar.setText("Regístrate");
		BtnRegistrar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		BtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				BtnRegistrarActionPerformed(evt);
			}
		});

		jPanel2.setBackground(new java.awt.Color(204, 204, 255));
		jPanel2.setForeground(new java.awt.Color(0, 153, 255));

		jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(255, 255, 255));
		jLabel1.setText("FORMULARIO DE REGISTRO");

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addGap(194, 194, 194).addComponent(jLabel1)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addGap(18, 18, 18).addComponent(jLabel1)
						.addContainerGap(19, Short.MAX_VALUE)));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(
						jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jPanel1Layout
												.createSequentialGroup().addContainerGap().addComponent(jPanel2,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
										.addGroup(jPanel1Layout.createSequentialGroup().addGap(27, 27, 27)
												.addGroup(jPanel1Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(lblConfContraseña).addComponent(lblContraseña)
														.addComponent(lblConfEmail).addComponent(lblEmail)
														.addComponent(lblResidencia1).addComponent(lblNumCel)
														.addComponent(lblResidencia)
														.addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE,
																56, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(TxtNombre).addComponent(TxtApellidos)
														.addComponent(lblApellidos1,
																javax.swing.GroupLayout.PREFERRED_SIZE, 56,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(lblTipoID)
														.addComponent(CombID, 0, javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(TxtNumID).addComponent(lblNumID)
														.addComponent(CombResidencia, 0,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(TxtNumCel)
														.addComponent(CombNacionalidad, 0,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(TxtEmail).addComponent(TxtConfEmail)
														.addComponent(TxtContraseña).addComponent(TxtConfContraseña)
														.addComponent(CBoxPTI, javax.swing.GroupLayout.DEFAULT_SIZE,
																591, Short.MAX_VALUE)
														.addComponent(CheckBoxTyC))
												.addGap(0, 44, Short.MAX_VALUE)))
										.addContainerGap())
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel1Layout.createSequentialGroup().addGap(93, 93, 93)
												.addComponent(BtnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 178,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(99, 99, 99)
												.addComponent(BtnMetodos, javax.swing.GroupLayout.PREFERRED_SIZE, 178,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(10, 10, 10)
						.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(30, 30, 30).addComponent(lblNombre)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(30, 30, 30).addComponent(lblApellidos1)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(TxtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(30, 30, 30).addComponent(lblTipoID)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(CombID, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(30, 30, 30).addComponent(lblNumID)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(TxtNumID, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(30, 30, 30).addComponent(lblResidencia)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(CombResidencia, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(30, 30, 30).addComponent(lblNumCel)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(TxtNumCel, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(30, 30, 30).addComponent(lblResidencia1)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(CombNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(30, 30, 30).addComponent(lblEmail)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(TxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(30, 30, 30).addComponent(lblConfEmail)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(TxtConfEmail, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(30, 30, 30).addComponent(lblContraseña).addGap(18, 18, 18)
						.addComponent(TxtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(30, 30, 30).addComponent(lblConfContraseña)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(TxtConfContraseña, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(30, 30, 30)
						.addComponent(CBoxPTI, javax.swing.GroupLayout.PREFERRED_SIZE, 29,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(CheckBoxTyC)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(BtnMetodos, javax.swing.GroupLayout.PREFERRED_SIZE, 43,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(BtnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 43,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(20, Short.MAX_VALUE)));

		jScrollPane1.setViewportView(jPanel1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 684,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addComponent(jScrollPane1,
						javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 101, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void CBoxPTIActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_CBoxPTIActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_CBoxPTIActionPerformed

	private void CombNacionalidadActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_CombNacionalidadActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_CombNacionalidadActionPerformed

	private void CombResidenciaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_CombResidenciaActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_CombResidenciaActionPerformed

	private void CombIDActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_CombIDActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_CombIDActionPerformed

	private void BtnMetodosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BtnMetodosActionPerformed
		ArrayMetodos taller = new ArrayMetodos();
		taller.setMyList(myList);
		taller.setCont(ce);
		taller.metodos();

	}// GEN-LAST:event_BtnMetodosActionPerformed

	private void CheckBoxTyCActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_CheckBoxTyCActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_CheckBoxTyCActionPerformed

	private void BtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BtnRegistrarActionPerformed
		String Nombre = TxtNombre.getText();
		String Apellidos = TxtApellidos.getText();
		String TipoID = (String) CombID.getSelectedItem();
		String Identificacion = TxtNumID.getText();
		String Residencia = (String) CombResidencia.getSelectedItem();
		String Celular = TxtNumCel.getText();
		String Nacionalidad = (String) CombNacionalidad.getSelectedItem();
		String Email = TxtEmail.getText();
		String ConfEmail = TxtConfEmail.getText();
		String Contraseña = TxtContraseña.getText();
		String ConfContraseña = TxtConfContraseña.getText();
		// en este if deben haber metodos que envien los datos al array. se debe crear
		// otra clase pilas
		if (VAlcampos() == true) {

			Usuario object = new Usuario(Nombre, Apellidos, TipoID, Identificacion, Residencia, Celular, Nacionalidad,
					Email, Contraseña);
			myList.add(object);

			LimpiarCampos();
		}

	}// GEN-LAST:event_BtnRegistrarActionPerformed

	public boolean VAlcampos() {
		String Nombre = TxtNombre.getText();
		String Apellidos = TxtApellidos.getText();
		String TipoID = (String) CombID.getSelectedItem();
		String Identificacion = TxtNumID.getText();
		String Residencia = (String) CombResidencia.getSelectedItem();
		String Celular = TxtNumCel.getText();
		String Nacionalidad = (String) CombNacionalidad.getSelectedItem();
		String Email = TxtEmail.getText();
		String ConfEmail = TxtConfEmail.getText();
		String Contraseña = TxtContraseña.getText();
		String ConfContraseña = TxtConfContraseña.getText();

		// Validar Campos Vacios
		if (Nombre.equals("") || Apellidos.equals("") || TipoID.equals("SELECCIONE") || Identificacion.equals("")
				|| Residencia.equals("SELECCIONE") || Celular.equals("") || Nacionalidad.equals("") || Email.equals("")
				|| ConfEmail.equals("") || Contraseña.equals("") || ConfContraseña.equals("")) {
			JOptionPane.showMessageDialog(rootPane, "Hay campos vacios o sin seleccionar");
			return false;
		} else {

			if (CheckBoxTyC.isSelected() == false) {
				JOptionPane.showMessageDialog(rootPane,
						"Debes aceptar el acuerdo de terminos y condiciones" + " para registrarte");
				return false;

			} else {
				// Validar Nombre
				if (ValnomYape(Nombre) == false) {
					JOptionPane.showMessageDialog(rootPane, "El Nombre debe contener minimo dos digitos"
							+ " y no incluir numeros ni caracteres especiales");
					return false;
				}
				// Validar Apellidos
				if (ValnomYape(Apellidos) == false) {
					JOptionPane.showMessageDialog(rootPane, "El Apellido debe contener minimo dos digitos"
							+ " y no incluir numeros ni caracteres especiales");
					return false;
				}
				// Validar Identificacion
				if (ValID(Identificacion) == false) {
					JOptionPane.showMessageDialog(rootPane,
							"La identificacion debe contener entre 6 y 10 dígitos e incluir solo números.");
					return false;
				}
				// Validar Celular
				if (ValCel(Celular) == false) {
					JOptionPane.showMessageDialog(rootPane,
							"El numero de celular debe contener minimo 10 dígitos e incluir solo números.");
					return false;
				}
				// Validar Email
				if (ValCorreo(Email) == false) {
					JOptionPane.showMessageDialog(rootPane, "Verifica el correo electronico ingresado");
					return false;
				} else {
					if (Email.equals(ConfEmail)) {

					} else {
						JOptionPane.showMessageDialog(rootPane, "Los correos electronicos no coinciden");
						if (flag == 0) {
							ce++;
						}
						flag++;

						return false;
					}

				}
				// Validar Contraseña
				if (ValContraseña(Contraseña) == false) {
					JOptionPane.showMessageDialog(rootPane, "La contraseña debe tener al menos 8 caracteres"
							+ ", una minuscula, una mayuscula y un numero, y no debe contener caracteres especiales");
					return false;
				} else {
					if (Contraseña.equals(ConfContraseña)) {

					} else {
						JOptionPane.showMessageDialog(rootPane, "Las contraseñas no coinciden");
						return false;
					}
				}
				// Jaziel aca debe haber un metodo de otra clase que envie las veces que puso
				// correos diferentes (ce)

				return true;
			}
		} // Fin Val Campos vacios

	}

	public void LimpiarCampos() {
		TxtNombre.setText("");
		TxtApellidos.setText("");
		CombID.setSelectedItem("SELECCIONE");
		TxtNumID.setText("");
		CombResidencia.setSelectedItem("SELECCIONE");
		TxtNumCel.setText("");
		CombNacionalidad.setSelectedItem("Colombiano (a)");
		TxtEmail.setText("");
		TxtConfEmail.setText("");
		TxtContraseña.setText("");
		TxtConfContraseña.setText("");
		CBoxPTI.setSelected(false);
		CheckBoxTyC.setSelected(false);
		flag = 0;
	}

	public boolean ValnomYape(String n) {
		Pattern pattern = Pattern.compile(
				"^([A-Za-zÑñÁáÉéÍíÓóÚú]+['\\-]{0,1}[A-Za-zÑñÁáÉéÍíÓóÚú]+)(\\s+([A-Za-zÑñÁáÉéÍíÓóÚú]+['\\-]{0,1}[A-Za-zÑñÁáÉéÍíÓóÚú]+))*$");
		Matcher mather = pattern.matcher(n);
		return mather.find();
	}

	public boolean ValID(String Identificacion) {
		Pattern pattern = Pattern.compile("^[0-9]{6,10}$");
		Matcher mather = pattern.matcher(Identificacion);
		return mather.find();
	}

	public boolean ValCel(String Celular) {
		Pattern pattern = Pattern.compile("^\\d{" + "10,}$");
		Matcher mather = pattern.matcher(Celular);
		return mather.find();
	}

	public boolean ValCorreo(String Email) {
		Pattern pattern = Pattern.compile("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$");
		Matcher mather = pattern.matcher(Email);
		return mather.find();
	}

	public boolean ValContraseña(String Contraseña) {
		Pattern pattern = Pattern.compile("^(?=.*\\d)(?=.*[a-z])(?=.*[A-Z])[a-zA-Z\\d]{8,}$");
		Matcher mather = pattern.matcher(Contraseña);
		return mather.find();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(FormReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(FormReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(FormReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(FormReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new FormReg().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton BtnMetodos;
	private javax.swing.JButton BtnRegistrar;
	private javax.swing.JCheckBox CBoxPTI;
	private javax.swing.JCheckBox CheckBoxTyC;
	private javax.swing.JComboBox<String> CombID;
	private javax.swing.JComboBox<String> CombNacionalidad;
	private javax.swing.JComboBox<String> CombResidencia;
	private javax.swing.JTextField TxtApellidos;
	private javax.swing.JTextField TxtConfContraseña;
	private javax.swing.JTextField TxtConfEmail;
	private javax.swing.JTextField TxtContraseña;
	private javax.swing.JTextField TxtEmail;
	private javax.swing.JTextField TxtNombre;
	private javax.swing.JTextField TxtNumCel;
	private javax.swing.JTextField TxtNumID;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JLabel lblApellidos1;
	private javax.swing.JLabel lblConfContraseña;
	private javax.swing.JLabel lblConfEmail;
	private javax.swing.JLabel lblContraseña;
	private javax.swing.JLabel lblEmail;
	private javax.swing.JLabel lblNombre;
	private javax.swing.JLabel lblNumCel;
	private javax.swing.JLabel lblNumID;
	private javax.swing.JLabel lblResidencia;
	private javax.swing.JLabel lblResidencia1;
	private javax.swing.JLabel lblTipoID;
	// End of variables declaration//GEN-END:variables
}
